plugins = []
functionsDirectory = "/Users/joevitajose/Desktop/htsyndicate-app/functions"
functionsDirectoryOrigin = "config"
headers = []
redirects = []

[functions]

[functions."*"]
node_bundler = "esbuild"

[build]
publish = "/Users/joevitajose/Desktop/htsyndicate-app/dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"
functions = "/Users/joevitajose/Desktop/htsyndicate-app/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]